import { Header } from "@/components/Header";
import Link from "next/link";

export default function Home() {
	return (
		<div className="min-h-screen bg-gradient-to-br from-purple-50 via-pink-50 to-indigo-50">
			<Header />

			{/* Hero Section */}
			<section className="relative overflow-hidden">
				<div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-16">
					<div className="text-center">
						<h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
							Discover Your
							<span className="block bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
								Cosmic Path
							</span>
						</h1>
						<p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
							Unlock the secrets of the stars with AI-powered astrological
							insights. Get personalized readings, birth chart analysis, and
							cosmic guidance tailored just for you.
						</p>
						<div className="flex flex-col sm:flex-row gap-4 justify-center">
							<Link
								href="/auth/signin"
								className="px-8 py-4 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg text-lg font-semibold hover:from-purple-700 hover:to-pink-700 transition-all duration-200 shadow-lg hover:shadow-xl">
								Start Your Journey
							</Link>
							<Link
								href="/features"
								className="px-8 py-4 border-2 border-purple-600 text-purple-600 rounded-lg text-lg font-semibold hover:bg-purple-600 hover:text-white transition-all duration-200">
								Learn More
							</Link>
						</div>
					</div>
				</div>

				{/* Floating Elements */}
				<div className="absolute top-20 left-10 w-20 h-20 bg-purple-200 rounded-full opacity-20 animate-pulse"></div>
				<div className="absolute top-40 right-20 w-16 h-16 bg-pink-200 rounded-full opacity-30 animate-bounce"></div>
				<div className="absolute bottom-20 left-1/4 w-12 h-12 bg-indigo-200 rounded-full opacity-25 animate-pulse"></div>
			</section>

			{/* Features Section */}
			<section className="py-20 bg-white">
				<div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
					<div className="text-center mb-16">
						<h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
							What Makes Us Special
						</h2>
						<p className="text-xl text-gray-600 max-w-2xl mx-auto">
							Experience the perfect blend of ancient wisdom and modern AI
							technology
						</p>
					</div>

					<div className="grid md:grid-cols-3 gap-8">
						<div className="text-center p-6 rounded-xl bg-gradient-to-br from-purple-50 to-pink-50">
							<div className="w-16 h-16 bg-gradient-to-br from-purple-600 to-pink-600 rounded-full flex items-center justify-center mx-auto mb-4">
								<span className="text-white text-2xl">★</span>
							</div>
							<h3 className="text-xl font-semibold text-gray-900 mb-2">
								AI-Powered Readings
							</h3>
							<p className="text-gray-600">
								Get personalized astrological insights generated by advanced AI,
								combining traditional astrology with modern interpretation.
							</p>
						</div>

						<div className="text-center p-6 rounded-xl bg-gradient-to-br from-purple-50 to-pink-50">
							<div className="w-16 h-16 bg-gradient-to-br from-purple-600 to-pink-600 rounded-full flex items-center justify-center mx-auto mb-4">
								<span className="text-white text-2xl">🔮</span>
							</div>
							<h3 className="text-xl font-semibold text-gray-900 mb-2">
								Birth Chart Analysis
							</h3>
							<p className="text-gray-600">
								Discover your unique cosmic blueprint with detailed natal chart
								analysis and planetary interpretations.
							</p>
						</div>

						<div className="text-center p-6 rounded-xl bg-gradient-to-br from-purple-50 to-pink-50">
							<div className="w-16 h-16 bg-gradient-to-br from-purple-600 to-pink-600 rounded-full flex items-center justify-center mx-auto mb-4">
								<span className="text-white text-2xl">✨</span>
							</div>
							<h3 className="text-xl font-semibold text-gray-900 mb-2">
								Daily Guidance
							</h3>
							<p className="text-gray-600">
								Receive daily horoscopes and transit readings to navigate life's
								challenges with cosmic wisdom.
							</p>
						</div>
					</div>
				</div>
			</section>

			{/* How It Works Section */}
			<section className="py-20 bg-gradient-to-br from-purple-50 to-pink-50">
				<div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
					<div className="text-center mb-16">
						<h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
							How It Works
						</h2>
						<p className="text-xl text-gray-600 max-w-2xl mx-auto">
							Three simple steps to unlock your cosmic potential
						</p>
					</div>

					<div className="grid md:grid-cols-3 gap-8">
						<div className="text-center">
							<div className="w-20 h-20 bg-gradient-to-br from-purple-600 to-pink-600 rounded-full flex items-center justify-center mx-auto mb-4 text-white text-2xl font-bold">
								1
							</div>
							<h3 className="text-xl font-semibold text-gray-900 mb-2">
								Enter Your Details
							</h3>
							<p className="text-gray-600">
								Provide your birth date, time, and location to create your
								unique astrological profile.
							</p>
						</div>

						<div className="text-center">
							<div className="w-20 h-20 bg-gradient-to-br from-purple-600 to-pink-600 rounded-full flex items-center justify-center mx-auto mb-4 text-white text-2xl font-bold">
								2
							</div>
							<h3 className="text-xl font-semibold text-gray-900 mb-2">
								AI Analysis
							</h3>
							<p className="text-gray-600">
								Our AI processes your birth chart and generates personalized
								insights and readings.
							</p>
						</div>

						<div className="text-center">
							<div className="w-20 h-20 bg-gradient-to-br from-purple-600 to-pink-600 rounded-full flex items-center justify-center mx-auto mb-4 text-white text-2xl font-bold">
								3
							</div>
							<h3 className="text-xl font-semibold text-gray-900 mb-2">
								Discover Insights
							</h3>
							<p className="text-gray-600">
								Explore your personalized readings, daily guidance, and cosmic
								wisdom.
							</p>
						</div>
					</div>
				</div>
			</section>

			{/* CTA Section */}
			<section className="py-20 bg-gradient-to-r from-purple-600 to-pink-600">
				<div className="max-w-4xl mx-auto text-center px-4 sm:px-6 lg:px-8">
					<h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
						Ready to Discover Your Cosmic Path?
					</h2>
					<p className="text-xl text-purple-100 mb-8">
						Join thousands of users who have unlocked their astrological
						potential
					</p>
					<Link
						href="/auth/signin"
						className="px-8 py-4 bg-white text-purple-600 rounded-lg text-lg font-semibold hover:bg-gray-100 transition-all duration-200 shadow-lg hover:shadow-xl">
						Start Your Free Reading
					</Link>
				</div>
			</section>

			{/* Footer */}
			<footer className="bg-gray-900 text-white py-12">
				<div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
					<div className="grid md:grid-cols-4 gap-8">
						<div>
							<div className="flex items-center space-x-2 mb-4">
								<div className="w-8 h-8 bg-gradient-to-br from-purple-600 to-pink-600 rounded-lg flex items-center justify-center">
									<span className="text-white font-bold text-sm">★</span>
								</div>
								<span className="text-xl font-bold">Astrology AI</span>
							</div>
							<p className="text-gray-400">
								Discover your cosmic path with AI-powered astrological insights.
							</p>
						</div>

						<div>
							<h3 className="text-lg font-semibold mb-4">Features</h3>
							<ul className="space-y-2 text-gray-400">
								<li>
									<Link
										href="/features"
										className="hover:text-white transition-colors">
										Birth Chart Analysis
									</Link>
								</li>
								<li>
									<Link
										href="/features"
										className="hover:text-white transition-colors">
										AI Readings
									</Link>
								</li>
								<li>
									<Link
										href="/features"
										className="hover:text-white transition-colors">
										Daily Horoscopes
									</Link>
								</li>
								<li>
									<Link
										href="/features"
										className="hover:text-white transition-colors">
										Compatibility
									</Link>
								</li>
							</ul>
						</div>

						<div>
							<h3 className="text-lg font-semibold mb-4">Company</h3>
							<ul className="space-y-2 text-gray-400">
								<li>
									<Link
										href="/about"
										className="hover:text-white transition-colors">
										About
									</Link>
								</li>
								<li>
									<Link
										href="/privacy"
										className="hover:text-white transition-colors">
										Privacy
									</Link>
								</li>
								<li>
									<Link
										href="/terms"
										className="hover:text-white transition-colors">
										Terms
									</Link>
								</li>
								<li>
									<Link
										href="/contact"
										className="hover:text-white transition-colors">
										Contact
									</Link>
								</li>
							</ul>
						</div>

						<div>
							<h3 className="text-lg font-semibold mb-4">Connect</h3>
							<ul className="space-y-2 text-gray-400">
								<li>
									<Link
										href="/blog"
										className="hover:text-white transition-colors">
										Blog
									</Link>
								</li>
								<li>
									<Link
										href="/support"
										className="hover:text-white transition-colors">
										Support
									</Link>
								</li>
								<li>
									<Link
										href="/community"
										className="hover:text-white transition-colors">
										Community
									</Link>
								</li>
							</ul>
						</div>
					</div>

					<div className="border-t border-gray-800 mt-8 pt-8 text-center text-gray-400">
						<p>&copy; 2024 Astrology AI. All rights reserved.</p>
					</div>
				</div>
			</footer>
		</div>
	);
}
